# Import Library

import streamlit as st
import numpy as np
import pickle
import easyocr
import pdfplumber
from PIL import Image
import time
import itertools
import re

# Web Browser Tab config

st.set_page_config(
    page_title="AI-Powered Real/Fake News Detector",
    page_icon="🤖"
)


# Load Model TF-IDF and Easyocr

@st.cache_resource
def load_resource():
    
    with open("model/model.pkl", "rb") as f:
        model = pickle.load(f)
        
    with open("model/tfidf.pkl", "rb") as f:
        tfidf = pickle.load(f)
        
    reader = easyocr.Reader(["en"])
        
    return model, tfidf, reader

model, tfidf, reader = load_resource()


# Custom Loader/Spinner    
    
def loader():
    
    placeholder = st.empty()
    
    seconds = 4

    for dots in itertools.cycle([".", "..", "...", "...."]):
        placeholder.info(f"🔍 Analyzing{dots}")
        time.sleep(0.5)
        seconds -= 0.6
        if seconds <= 0:
            break

    # Remove the "Analyzing..." message
    placeholder.empty()
     
# Text Preprocessing

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# Create the function for text extraction from PDF

def text_extract_from_pdf(uploaded_pdf):
    try:
        text_data = []
        with pdfplumber.open(uploaded_pdf) as pdf:
            for page in pdf.pages:
                extract_data = page.extract_text()
                
                if extract_data:
                    text_data.append(extract_data)
                    
            extracted_data = "\n".join(text_data)
            
            if extracted_data.strip():
                
                st.success("✅️ Text extracted is successfully!")
                with st.expander("View Extracted Text"):
                    st.text_area("Extracted News Article", value=extracted_data, height=200, disabled=True)
            
            return extracted_data
              
    except Exception as e:
        st.error(f"🚨 Could not read PDF {e}")
        return ""
        
# Create the function for text extraction from Image

def text_extract_from_img(uploaded_img):
    
    try :
        image = Image.open(uploaded_img)
        image = np.array(image)
        data = reader.readtext(image)
        text_data = []
    
        for item in data:
            text_data.append(item[1])
    
        extracted_data = "\n".join(text_data)
    
        if extracted_data.strip():
          
            st.success("✅️ Text extracted is successfully!")
            with st.expander("📋 View Extracted Text"):
                st.text_area("Extracted News Article", value=extracted_data, height=200, disabled=True)
            
        return extracted_data
    
    except Exception as e:
        st.error(f"🚨 Could not read Image {e}")
        return ""

# Create the function for prediction of the model 

def pred_model(text_data):
    
    try:  
        
        text_clean = clean_text(text_data)
        
        tfidf_text = tfidf.transform([text_clean])
        prediction = model.predict(tfidf_text)[0]
    
        if prediction == 0:
            st.warning("📛 Fake News")
        else:
            st.success("✅ Real News")
            
        st.info("**📢Disclaimer:** ***This prediction is generated by a Machine Learning model and is intended for informational purposes only. It may not always be accurate. Please verify important news using trusted and reliable sources.***")

    except Exception as e:
        st.error(f"🚨 Prediction failed: {e}")
    


# Header 

st.title("📰 AI-Powered News Detector")
st.write("🔍 Detect the News is Real and Fake using Machine Learning.")


# Default Variable 

news_text = ""

# Input Method

input_method = st.radio("Choose input method",["✍️ Paste News","📄 Upload PDF","🖼️ Upload Image"], horizontal=True)


# Condition matching

if input_method == "✍️ Paste News":

    news_text = st.text_area("📝 Enter the News Article Text ", height=200)
    
elif input_method == "📄 Upload PDF":
    uploaded_pdf = st.file_uploader("📤 Upload the PDF", type=["pdf"])
    
    if uploaded_pdf:
        
        with st.spinner("Extracting text from PDF...."):
            news_text = text_extract_from_pdf(uploaded_pdf)
    
elif input_method == "🖼️ Upload Image":
    
    uploaded_img = st.file_uploader("📤 Upload the image", type=["png","jpg", "jpeg"])
    
    if uploaded_img:
        
        with st.spinner("Extracting text from image...."):
            news_text = text_extract_from_img(uploaded_img)

# Button

if st.button("🕵️ Analyze News", use_container_width=True):
    
    if not news_text or not news_text.strip():
        
        st.warning("⚠️ Please enter News Article")
        
    elif len(news_text.split()) < 10:
        
        st.warning("‼️ Please enter at least 10 words")
        
    else:
        
        loader()
        pred_model(news_text)
        